version: '3.8'

services:
  friend-lines-app:
    build: .
    container_name: friend-lines-server
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3005/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - friend-lines-network

networks:
  friend-lines-network:
    driver: bridge
