services:
  - type: web
    name: friend-lines-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3005
    healthCheckPath: /health
    autoDeploy: true
    branch: main
